enum statusOrder{
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
    CANCEL = 'CANCEL',
    FINISHED = 'FINISHED',
    SHIPPING = 'SHIPPING',
    WAITING = 'WAITING',
    SHIPPING_SUCCESS = 'SHIPPING_SUCCESS',
    SHIPPING_FAIL = 'SHIPPING_FAIL',
    SHIPPING_CANCEL = 'SHIPPING_CANCEL',
    SHIPPING_RETURN = 'SHIPPING_RETURN',
}

export default statusOrder;