version: '3'
services:
  app:
    image: node:20.5
    container_name: test_app
    restart: always
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongo
    networks:
      - app-network
    gitenvironment:
      - SEED_ON_START=true
  mongo:
    image: mongo
    container_name: mongo_test
    ports:
      - "27017:27017"    
    volumes:
      - ./data:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge


