version: '3'
services:
  app:
    image: node:20.5
    container_name: test_app
    restart: always
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: redis
    container_name: redis_test
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge


